export const apiPath = {
  BANNERS: "/api/QuanLyPhim/LayDanhSachBanner",
  MOVIES: "/api/QuanLyPhim/LayDanhSachPhim",
  CINEMAS: "/api/QuanLyRap/LayThongTinHeThongRap",
  CINEMA_SCHEDULE: "/api/QuanLyRap/LayThongTinLichChieuHeThongRap",
  MOVIE_DETAIL: "/api/QuanLyRap/LayThongTinLichChieuPhim",
  LOGIN: "/api/QuanLyNguoiDung/DangNhap",
  SIGNUP: "/api/QuanLyNguoiDung/DangKy",
  BOOKING: "/api/QuanLyDatVe/LayDanhSachPhongVe",
  CINEMA_CLUSTER: "/api/QuanLyRap/LayThongTinCumRapTheoHeThong",
  DELETE_MOVIE: "/api/QuanLyPhim/XoaPhim",
  CREATE_MOVIE: "/api/QuanLyPhim/ThemPhimUploadHinh",
  BOOKING_SEAT: "/api/QuanLyDatVe/DatVe",
  USER_PROFILE: "/api/QuanLyNguoiDung/ThongTinTaiKhoan",
  USER_UPDATE_INFO: "/api/QuanLyNguoiDung/CapNhatThongTinNguoiDung",
  UPDATE_MOVIE: "/api/QuanLyPhim/CapNhatPhimUpload",
  SET_MOVIE_SCHEDULE: "/api/QuanLyDatVe/TaoLichChieu",
  USER_ADD: "/api/QuanLyNguoiDung/ThemNguoiDung",
  USER_DELETE: "/api/QuanLyNguoiDung/XoaNguoiDung",
  ALL_USER_INFO: "/api/QuanLyNguoiDung/LayDanhSachNguoiDung",
  USER_PROFILE_BY_ID: "/api/QuanLyNguoiDung/LayThongTinNguoiDung",
  SEARCH_USER_BY_ID: "/api/QuanLyNguoiDung/TimKiemNguoiDung",
};
